name: bloblist
description: "TodoList X Tamagochi"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number (separated by +).
version: 0.1.0+1

environment:
  sdk: ^3.8.1

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# To see which dependencies have newer versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  flutter_native_splash: 2.4.6 # To have a nice splash screen for launch
  go_router: ^15.2.4
  provider: ^6.1.5
  foundation: ^0.0.5
  logging: ^1.3.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  back_button_interceptor: ^8.0.4
  intl: any
  flutter_3d_controller: ^2.2.0
  flutter_launcher_icons: ^0.14.4
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  flutter_lints: ^6.0.0

#Splash config for native Splash
flutter_native_splash:
  color: "#311B92" # Or color: "your_color_hex" or color: "your_color_name"
  image: images/ic_launcher.png
  android_12:
    color: "#311B92"
    image: images/ic_launcher.png

# The following section is specific to Flutter packages.
flutter:
  generate: true # For i18n
  uses-material-design: true
  assets:
    - images/
    - assets/dq_slime.glb
    - assets/dq_boing.mp3
    - assets/tasks.json

  fonts:
    - family: GuavaCandy
      fonts:
        - asset: assets/fonts/GuavaCandy.ttf
